### ISSUE TITLE
Please make the add-on e10s/multiprocess compatible!

### ISSUE THREAD

**Issue by Quantum00** [mustafakalash/royt#10]
It is currently not compatible. Could you please add e10s support?

**Comment by ion201** [comment]
It seems like this addon is already e10s compatible - I've been using it with e10s enabled for a while without any issues. @mustafakalash , all you need to do is add the flag to `package.json`

    "permissions": {
        "multiprocess": true
    }

**Comment by mustafakalash** [comment]
Done.
