### ISSUE TITLE
Does not load when opening a video in a new tab.

### ISSUE THREAD

**Issue by niilohlin** [mustafakalash/royt#13]
1. Go to youtube with the plugin installed. 
2. Open a video in a new tab. 
3. Switch to that tab.

*Result:* Youtube commets are still present.
*Expected:* Youtube commets replaced with reddit comments.

If you open the same video with by clicking on it. The plugin works as expected.

**Comment by mustafakalash** [comment]
Possibly related to #9 if this is still an issue.

**Comment by mustafakalash** [comment]
Reproduced on the new layout.
