### ISSUE TITLE
Preferences not saved for ESR builds

### ISSUE THREAD

**Issue by 794** [mustafakalash/royt#15]
[Screenshot here.](http://puu.sh/xt4Jc/3b2a522617.png)

As you can see, it won't let me switch to Google+ comments, the button for it is gone. If there isn't a reddit post made for the video it'll just say "no posts found" and I can't switch to normal YouTube comments.

Also, while it isn't as big a deal, it also says "commenting as: undefined" instead of my username.

Using Firefox 52.3 ESR.

**Comment by mustafakalash** [comment]
You need to enable the switch to Google+ button in the options. Head to about:addons and click on options next to the entry for Reddit on YouTube. You can customize these settings there. Please let me know if this doesn't resolve your issue.

**Comment by 794** [comment]
Ticking those options has no effect. After clicking 'save', then closing and reopening the options the boxes are unticked again.

**Comment by mustafakalash** [comment]
I've been able to reproduce this issue specifically with the ESR build, thank you.

**Comment by mustafakalash** [comment]
For version 52.3, you must manually enable the storage API used by Reddit on YouTube's preferences. Please follow these instructions:
1. Type `about:config` into the URL bar
1. Click "I accept the risk!"
1. Search `storage.sync` and double click `webextensions.storage.sync.enabled` so that its value is `true`

**Comment by 794** [comment]
Great, that's fixed it. Thanks for actually finding the fix. Another dev of an add-on I had a problem with recently just said "oh well figure it out yourself". So thanks again for going to the length of solving this!
