### ISSUE TITLE
Collapsing comments causes them to disappear

### ISSUE THREAD

**Issue by losuler** [mustafakalash/royt#16]
### Bug description
Collapsing Reddit comments causes them to disappear instead of collapsing them. From memory, this didn't occur prior to version 2.0.0.

### Steps to reproduce
- Press the collapse comment button, which looks like the following `[-]`. 
(Occurs to any comment, regardless of it's hierarchy).

**Actual result:** The comment disappears from the thread until refreshed.
**Expected result:** The comment collapsing, the button changing to `[+]` for uncollapsing.

### Platform info

**Operating System**: Debian GNU/Linux testing (buster)
**Browser**: Firefox 55.0.3 (64-bit)
(Tested on a clean profile, with no other addons installed or customizations made).
**Reddit on Youtube version:** 2.0.0

*Edit: Added platform info.*

**Comment by mustafakalash** [comment]
Unable to reproduce with 55.0.3 (32-bit) on Windows 10. Does this issue always occur for you?

**Comment by losuler** [comment]
It was silly of me not to check for this originally, but it appears this is being caused by the new YouTube layout (which also seems to be causing some other issues with this add-on).

Is compatibility with the new layout something you are presently working on?

**Comment by mustafakalash** [comment]
I'll look into it, thanks.
