### ISSUE TITLE
Addon broken

### ISSUE THREAD

**Issue by Portal90** [mustafakalash/royt#17]
Since the last Youtube update this Addon doesn't work anymore

Any chance far a fix?

**Comment by Portal90** [comment]
Im sorry im just stupid. It was my own fault.

Just one question. How can i switch from Reddit to youtube comments?
The option "show the google+ comments button" doesn't work for me.

**Comment by mustafakalash** [comment]
Can you please tell me which version of Firefox you are using, and in what way your preferences aren't working?

**Comment by Portal90** [comment]
I use FF 56.0b11 (64-Bit) Beta. I don't realy understand it. your addon was broken for me even after 3-4 restarts of FF for the same video but since the the last restarts it works perfectly.

Thank you for keeping this Addon up to date.

**Comment by mustafakalash** [comment]
We can probably chalk that up to beta weirdness. Thanks for your reply.
