### ISSUE TITLE
Missing option to view youtube comments

### ISSUE THREAD

**Issue by ceribik** [mustafakalash/royt#19]
With the pre-webext addon, you used to be able to click a button to show the YouTube comments. It's no longer possible and should be readded.

**Comment by mustafakalash** [comment]
Please go to about:addons and click options next to Reddit on YouTube and enable the option to show the YouTube comments button, then click save.

**Comment by ceribik** [comment]
Thanks. I did see those options earlier, but I mistook "Google+" as being unrelated to youtube comments. IMO they should be enabled by default.

**Comment by mustafakalash** [comment]
Glad you worked it out.
