### ISSUE TITLE
Repository name still references AlienTube

### ISSUE THREAD

**Issue by jgandert** [mustafakalash/royt#2]
The repository needs to be renamed.

btw. Thanks for maintaining this addon for Firefox. (If that's what you plan to do.)

**Comment by mustafakalash** [comment]
I need to change some of the code to fit Mozilla's standards before this addon returns to the addon market. Hopefully I can do this as soon as I have some free time. Other than that, the repo name's fixed, thanks.

**Comment by jgandert** [comment]
@hockeygoalie5 Nice! :+1: 

How long do you think this will take?

**Comment by mustafakalash** [comment]
It's available on the market right now.

**Comment by jgandert** [comment]
@hockeygoalie5 Cool, thanks for your work! :)
