### ISSUE TITLE
Does not respond to new yt design's dark mode

### ISSUE THREAD

**Issue by Gotolei** [mustafakalash/royt#20]
RoYT 2.1.0, Fx 55.0.2

Not sure what further details to give. Even after disabling ad blocker and userscripts (what else might be conflicting with it?)
From what I can tell it still works if the `darkmode` class is manually added on, but whatever method it's using to pick it out isn't actually detecting it.

https://streamable.com/as2zm

--
And speaking of the dark mode, the styling of the textbox and nearby buttons could use some work. Mostly, setting the buttons to a similarly-dark color and getting rid of the beveled borders:
![image](https://user-images.githubusercontent.com/7553595/30515858-70ab9d34-9b1f-11e7-9f89-c4329834e162.png)

**Comment by mustafakalash** [comment]
I haven't coded in any support for dark mode, yet.

**Comment by HenryTheVacuum** [comment]
Soon? :)

**Comment by mustafakalash** [comment]
@jesse9212 I added dark mode support a few years ago. I tested it just now and it is working for me. If that's not the case for you, then please make a bug report.
