### ISSUE TITLE
v2.20 not working for me

### ISSUE THREAD

**Issue by icheyne** [mustafakalash/royt#22]
First of all thanks so much for updating this awesome extension.

Unfortunately this new version from the addons store isn't working for me. I load up a video from Trending which has many submissions and comments on Reddit, but I am told there are "no posts found".

https://youtu.be/D59v74k5flU

If I go to http://reddit.com/https://www.youtube.com/watch?v=D59v74k5flU then there is only one submission with zero comments. Is this the reason why?

I enabled the option to show G+ comments if there are no Reddit comments and then it shows the G+ comments, but it does **not** show the G+ button if that option is enabled.

Firefox 55.0.3 (64-bit)

**Comment by mustafakalash** [comment]
Can I close this, as your problem being explained by #23?

**Comment by icheyne** [comment]
I tried it with uBlock disabled and it still doesn't work.

**Comment by mustafakalash** [comment]
The addon seems to load correctly and look for threads, and says that it could not find any? On the video you provided, I can see 17 results on a clean install of 55.0.3 (64-bit).

**Comment by Devorlon** [comment]
Just recreated with 55.03 (64bit) fresh install, shows G+ comments with or without enabling.

Using Ryzen 1700 and GTX 1080 with Windows 10 Pro 64bit

EDIT: After reinstalling everything it's working again

**Comment by icheyne** [comment]
It just loads the G+ comments. Should I reset Firefox? Is there any debug info I can send you?

**Comment by mustafakalash** [comment]
Try uninstalling the addon and then reinstalling it as Devorlon suggests.

**Comment by icheyne** [comment]
Didn't work.

**Comment by mustafakalash** [comment]
Do you see the "show reddit comments on this channel" checkbox near the subscribe button? I ask because this would indicate if the addon was failing to load at all.

**Comment by icheyne** [comment]
If I disable and enable my other addons and restart the browser, sometimes the "show reddit comments on this channel" checkbox appears and sometimes G+ comments load. I can't find a pattern.

It doesn't work on my office laptop either.

**Comment by HifeFish** [comment]
On my main profile, the Addon has stopped working altogether with both old and new Youtube layouts.

On a clean Firefox profile (with new YT layout): When I click the youtu.be-link from OP, I get redirected to https://www.youtube.com/watch?v=D59v74k5flU&feature=youtu.be and I see G+ comments (even if the Addon is set to never display G+ comments). If I refresh or go directly to the above youtube.com link, I get the comments from http://reddit.com/r/notalkingvideos/comments/78gw74/primitive_technology_mud_bricks_1046/ (but none of the other 10 threads DuplicateBot posted, that are probably more interesting).
