### ISSUE TITLE
Incompatible with uBlock Origin

### ISSUE THREAD

**Issue by icheyne** [mustafakalash/royt#23]
1. Install uBlock Origin
1. Install royt
1. Open https://youtu.be/D59v74k5flU

royt does not display and regular G+ comments are shown

Firefox 55.0.3 (64-bit)
uBlock Origin 1.14.10
Reddit on Youtube Options, version 2.2.0

**Comment by mustafakalash** [comment]
I did not find any issue while using a clean install of uBlock Origin 1.14.10. Is there a change to the settings you have made which could explain the problem?

**Comment by icheyne** [comment]
I'm in advanced mode with 3rd party scripts and frames blocked?

https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode

**Comment by icheyne** [comment]
OK I tried it on another PC and this time it worked. Sorry!
