### ISSUE TITLE
Text size too tiny?

### ISSUE THREAD

**Issue by iiiGerardoiii** [mustafakalash/royt#26]
Any reason why all the text on this Add-on is tiny?

I think the comments should be 14px for a proper, comfortable reading. They're currently 10px by default, and the options below each comment have even smaller text.

**Comment by iiiGerardoiii** [comment]
Here's how it looks like on my FF 57 (using royt v2.2.0):
![captura de pantalla 2017-11-28 10 46 33](https://user-images.githubusercontent.com/6264194/33332350-b299389e-d429-11e7-87e8-53b696e8b14c.png)

To compare, this is youtube's comment section:
![captura de pantalla 2017-11-28 10 47 52](https://user-images.githubusercontent.com/6264194/33332398-cfd730fa-d429-11e7-9685-df0e6b9044bc.png)

**Comment by mustafakalash** [comment]
I see what you mean now. I have no issue with increasing the text size. I'll do so when I can.

**Comment by AIndoria** [comment]
Seconding this issue. 
The text on the videos is absolutely tiny.

**Comment by nklmilojevic** [comment]
It would be awesome if you could enlarge the font size.

**Comment by indeedwatson** [comment]
It would be ideal to have a setting where users can enter the font size they want.
