### ISSUE TITLE
Unable to save settings. 

### ISSUE THREAD

**Issue by MitchRuns** [mustafakalash/royt#27]
I go to options and attempt to check the boxes for enabling the Google+ comment icon but the settings aren't saving. The boxes stay unchecked and it reverts back to everything being blank. 

https://i.imgur.com/67jniyC.png

Then I check the video to see if it worked.

https://i.imgur.com/p7zotvs.png

Then I go back to settings to see the settings are back to this

https://i.imgur.com/eY1f206.png

On Firefox 57.0 (64-bit)

**Comment by waterpew** [comment]
I see the same issue - I cannot enable the "show google+ button" because the settings don't save.
I am running Firefox 52.7.

**Comment by mustafakalash** [comment]
Is any one still experiencing this issue? I have never been able to get it to happen.
