### ISSUE TITLE
ROYT not using the most-upvoted link

### ISSUE THREAD

**Issue by shelt** [mustafakalash/royt#29]
To reproduce, go to [this video](https://www.youtube.com/watch?v=wLjza0c-ykQ):

### Expected

The comments for the /r/h3h3productions tab should be [this thread](https://www.reddit.com/r/h3h3productions/comments/7xuxc7/the_dumbest_products_of_all_time/), which has 4314 points.

### Instead

The comments are for [this thread](http://reddit.com/r/h3h3productions/comments/7xuzhk/the_dumbest_products_of_all_time/), which has 0 points.

**Comment by mustafakalash** [comment]
On the video you provided, I am currently seeing the higher upvoted thread. Are you still seeing this issue, on this or another video?

**Comment by t0stiman** [comment]
i also see the higher upvoted thread.

**Comment by shelt** [comment]
It's now the correct thread for me as well, and I haven't seen the issue since. Must've been some one-off glitch.
