### ISSUE TITLE
Text is enormous in 2.3.0

### ISSUE THREAD

**Issue by fatalicus** [mustafakalash/royt#31]
After the latest update that happened, the text for reddit comments is enormous.

I see that the latest updates were supposed to fix an issue with small text (something i personally haven't seen), but this might have taken it too far.

Here is an image showing some different text, just to show how huge the text is compared to uyoutube in general:

![text size](https://user-images.githubusercontent.com/6996009/40039413-a322b522-5816-11e8-967d-7ab8f6f022ba.PNG)

**Comment by t0stiman** [comment]
Same bug here. Worked fine before latest update.
I use the old youtube design btw.

**Comment by zjeffer** [comment]
Same here, using old youtube design as well.

**Comment by ghost** [comment]
Workaround: https://addons.mozilla.org/en-GB/firefox/addon/reddit-on-youtube/versions/ revert to 2.2.0. 

This update burned my eyes, please add a custom font size option.

**Comment by mustafakalash** [comment]
The font issue was with the new layout, so making it normal sized there made it too big on the old layout. I was recently locked out of using the old layout, so I thought they were forcing every one over.

**Comment by t0stiman** [comment]
@mustafakalash you can still use the old layout with [this userscript](https://greasyfork.org/en/scripts/34818-youtube-restore-classic/code) or [this one](https://www.reddit.com/r/youtube/comments/82whs4/old_layout_option_gonegoogle_dead_to_me/dvddfem/)

**Comment by ghost** [comment]
I recommend the first userscript as it uses a cookie which tells youtube you're on the old design. The second one will break some features of youtube (the recommended section next to videos in particular).

**Comment by mustafakalash** [comment]
Thanks for the userscript. Update for this is going up.
