### ISSUE TITLE
Refresh button does not work

### ISSUE THREAD

**Issue by Hannah-GBS** [mustafakalash/royt#39]
Often I'll watch a video soon after it comes out, when there is little to no discussion on reddit.
But then by the time I've finished it there are some comments, but I have to refresh the whole page to load them.

It would be cool to have a button (either on the whole comment UI, or each subreddit tab) to refresh the thread.

This would also be useful for posting comments, as it's sometimes hard to tell if a posted comment is showing up without refreshing the page.

**Comment by mustafakalash** [comment]
I just remembered that there's a small refresh button underneath the thread title next to the other buttons. Can you confirm that this is working as expected?

**Comment by Hannah-GBS** [comment]
While I feel dumb for never noticing that button, I found after some testing that it doesn't seem to be working currently.
