### ISSUE TITLE
"Show more" button does not appear on youtube comments

### ISSUE THREAD

**Issue by jbdelphiki** [mustafakalash/royt#41]
![c80d9265bc01e5e26410f95e9d9738d3](https://user-images.githubusercontent.com/49620554/56097554-de234d80-5ec3-11e9-9251-ccdfe202c7e2.png)

I believe this is only when a reddit thread exists for a specified video, but am not currently sure. This is especially frustrating for watching full sets on youtube. Thanks so much in advance!

**Comment by mustafakalash** [comment]
I can see/use the "Read more"/"Show less" buttons in both light and dark themes. Can you look around and see if the button is showing on any comments at all? Please provide a link to this particular comment.

**Comment by jbdelphiki** [comment]
Update, it was my Stylish theme which I THOUGHT was just a simple reskin but turns out it was making extra modifications in the background, sorry for the confusion on my end!
