### ISSUE TITLE
Not working on latest Youtube update

### ISSUE THREAD

**Issue by Hannah-GBS** [mustafakalash/royt#43]
YouTube updated their video page somewhat recently (I'm not totally sure what changed, possibly something to do with Youtube Gaming links in descriptions), and ROYT has stopped working as a result. It doesn't load at all; the page appears as a regular YouTube comments page.

I think some parts of the page source have been renamed in this update, which is causing ROYT to not work. At a brief look, the div "#owner-container.style-scope.ytd-video-owner-renderer" is absent, and in fact the only instance of "#owner-container" is in reference to the sidebar in "#owner-container.ytd-playlist-sidebar-secondary-info-renderer".

I don't know enough about the script to dig any further, unfortunately.

**Comment by mustafakalash** [comment]
Thank you for your detailed report.
