### ISSUE TITLE
Reddit comments button causes youtube comments box to be misaligned

### ISSUE THREAD

**Issue by LitDub** [mustafakalash/royt#44]
When in youtube-comments mode, the Reddit Snew button is outside the card/box for comments, causing the right side to be misaligned.

![example - Copy](https://user-images.githubusercontent.com/25185376/65302733-06d20200-db4a-11e9-9db5-bec6dddba435.png)

I originally made this post about another issue but I solved it by updating (lol) so I've edited it to be about this instead.

**Comment by mustafakalash** [comment]
This is no longer a problem in the latest YouTube layout.
