### ISSUE TITLE
Show YouTube Comment Button not appearing

### ISSUE THREAD

**Issue by fenglengshun** [mustafakalash/royt#47]
Normal Window:
![image](https://user-images.githubusercontent.com/26621899/78637133-fad64380-78d3-11ea-8d78-9b782e2947b0.png)

On Private Window with only Reddit for YouTube allowed:
![image](https://user-images.githubusercontent.com/26621899/78637482-a2537600-78d4-11ea-9f8f-51b5397eb516.png)

Firefox 74.0.1 (64-bit) with extension Version 2.4.3 on Manjaro Linux KDE 19.0 x86_64 with Linux Kernel 5.5.13-1-MANJARO.

I had thought that it might have been a conflict with Iridium but that doesn't seem to be it.

**Comment by mustafakalash** [comment]
Just to be clear, did you go into "options" on the addon page and turn on "Show YouTube comments button?"

**Comment by fenglengshun** [comment]
> Just to be clear, did you go into "options" on the addon page and turn on "Show YouTube comments button?"

Sorry, only just now returned to Firefox, after trying out Vivaldi. I tried that and yeah, it works now. Was that option turned on by default or off? It should be on by default I think, though I'll admit that it might be me exporting my Firefox profile messing up the settings.

It took me a while to find the Preferences page because I don't think there's an icon for the extension and it didn't show up in the details page. Took me a while to figure out that I had to click the dropdown menu from the Add-Ons page then Preferences.

Maybe make an implementation like this? For extra discoverability. The details page is usually where I looked for Add-Ons option/preferences so I didn't even know there's one until it was pointed out, sorry.

![image](https://user-images.githubusercontent.com/26621899/89123515-312a7500-d4fa-11ea-9531-004d6b65c807.png)

**Comment by mustafakalash** [comment]
Thanks for pointing out this more visible option for the settings page. I didn't know it existed, even though doing it that way is the default! While I've rewritten a lot of the settings page, I never changed its configuration, so the defaults and the way it's displayed were set by the original author when he maintained a Firefox version. I'll move the settings page the next update, whenever that happens.
