### ISSUE TITLE
stopped working completely

### ISSUE THREAD

**Issue by Bluberius** [mustafakalash/royt#48]
It looks like the addon stopped working completely. 
The youtube comment section looks exactly the same with and without the addon.

**Comment by Hannah-GBS** [comment]
Same issue here

**Comment by mustafakalash** [comment]
The plugin is working on my end. Please post some information, such as the video in question, your Firefox version, what your settings are, and if there's any information in your browser console.

**Comment by Hannah-GBS** [comment]
For me:
Video: Any video, the reddit logo no longer appears at all
Firefox version: 77.0.1 (64 bit)
Settings: 
![image](https://user-images.githubusercontent.com/7504779/86524264-5632b600-be70-11ea-8b8d-abdc03009bd8.png)

Console on video page load: 
![image](https://user-images.githubusercontent.com/7504779/86524274-7bbfbf80-be70-11ea-8fd1-3d864e929078.png)

**Comment by ImmortalFishy** [comment]
I'm having the same issue on Firefox. I'm running 79.0b3 but have had it non-functioning for a few versions. The attached picture seems to imply there's some new security function preventing the addon from loading properly.

![firefox_ofgOxKt24E](https://user-images.githubusercontent.com/33342116/86575747-9a838c00-bf2c-11ea-8a10-f3e6e989a7c6.png)

**Comment by ImmortalFishy** [comment]
I'm having the same issue on Firefox. I'm running 79.0b3 but have had it non-functioning for a few versions. The attached picture seems to imply there's some security function preventing the addon from loading properly.
![firefox_ofgOxKt24E](https://user-images.githubusercontent.com/33342116/86576232-4fb64400-bf2d-11ea-9338-d7e15bb51960.png)

**Comment by mustafakalash** [comment]
I've tracked down the issue and an update will be out soon. @ImmortalFishy I did not see your errors during my testing, nor was the issue caused by permissions. After the update, if you still see those errors and the extension isn't working, please open a new issue.
