### ISSUE TITLE
[Request] Default to YT comments if no Reddit posts are found. 

### ISSUE THREAD

**Issue by I-Percy** [mustafakalash/royt#51]
I've noticed that when loading a video it defaults to selecting "Show Reddit posts on this channel" but many of the channels I watch don't have Reddit posts. I've also noticed that when "Show Reddit comments on this channel" is unselected there is a button to load reddit posts but not when it's the opposite so adding a "Load YT comments" would be very convenient. 

I am currently running version 2.4.5 of "Reddit on YouTube" on Firefox 87.0 (64-bit) on a Windows 10 PC and also a Linux PC.  

Thank you!

**Comment by mustafakalash** [comment]
There is a setting for this behavior. Access the options menu from Firefox's addons page:
![image](https://user-images.githubusercontent.com/313146/113191102-2829a900-922b-11eb-80ed-1a0711063bbb.png)
![image](https://user-images.githubusercontent.com/313146/113191132-2eb82080-922b-11eb-9660-c0bbdd43beaf.png)
