### ISSUE TITLE
Reddit for YouTube

### ISSUE THREAD

**Issue by ghost** [mustafakalash/royt#7]
Hello, I'm not sure if this is for everyone or just my Firefox, but the add on doesn't seem to work, where as the old version of alientube did.

My System Specs:

OS: Ubuntu 14.04
Browser: Firefox 45.0.1
Addons that also work on YouTube: Stylish (Dark Theme), YouTube+ Userscript, Hide Videos from YouTube (This isn't the problem)

**Comment by mustafakalash** [comment]
Tested working on 45.0.1 and even on 47.0a2.

Can you be more specific about your problem? Does it not load at all, try to load but fail, give an error?

**Comment by ghost** [comment]
It seems like the issue was YouTube+ showing youtube comments by default. I was able to fix it via hiding the YouTube comments completely!
